"""add user included

Revision ID: 489406e737e4
Revises: a76f635de7a3
Create Date: 2019-04-04 10:59:17.603667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '489406e737e4'
down_revision = 'a76f635de7a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('user_completed', sa.Boolean(), nullable=True))
    op.add_column('candidates', sa.Column('user_included', sa.Boolean(), nullable=True))
    op.drop_column('candidates', 'user_thanked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('user_thanked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('candidates', 'user_included')
    op.drop_column('candidates', 'user_completed')
    # ### end Alembic commands ###
