"""create candidates and edits tables

Revision ID: 4d282492c5e4
Revises: 
Create Date: 2019-04-02 15:59:09.400309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d282492c5e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edits',
    sa.Column('edit_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('lang', mysql.TINYTEXT(), nullable=True),
    sa.Column('rev_id', sa.Integer(), nullable=True),
    sa.Column('page_name', sa.TEXT(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('ores_damaging', sa.Boolean(), nullable=True),
    sa.Column('ores_goodfaith', sa.Boolean(), nullable=True),
    sa.Column('de_flagged', sa.Boolean(), nullable=True),
    sa.Column('de_flagged_algo_version', sa.Boolean(), nullable=True),
    sa.Column('edit_deleted', sa.Boolean(), nullable=True),
    sa.Column('diffHTML', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('newRevId', sa.Integer(), nullable=True),
    sa.Column('newRevDate', mysql.TINYTEXT(), nullable=True),
    sa.Column('newRevUser', mysql.TINYTEXT(), nullable=True),
    sa.Column('newRevComment', sa.TEXT(), nullable=True),
    sa.Column('oldRevId', sa.Integer(), nullable=True),
    sa.Column('oldRevDate', mysql.TINYTEXT(), nullable=True),
    sa.Column('oldRevUser', mysql.TINYTEXT(), nullable=True),
    sa.Column('oldRevComment', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('edit_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.drop_index('ix_twitter_statuses_created_at', table_name='twitter_statuses')
    op.drop_index('ix_twitter_statuses_record_created_at', table_name='twitter_statuses')
    op.drop_index('ix_twitter_statuses_user_id', table_name='twitter_statuses')
    op.drop_table('twitter_statuses')
    op.drop_index('ix_twitter_fills_record_created_at', table_name='twitter_fills')
    op.drop_index('ix_twitter_fills_user_id', table_name='twitter_fills')
    op.drop_table('twitter_fills')
    op.drop_index('ix_lumen_notice_to_twitter_user_notice_id', table_name='lumen_notice_to_twitter_user')
    op.drop_index('ix_lumen_notice_to_twitter_user_twitter_user_id', table_name='lumen_notice_to_twitter_user')
    op.drop_index('ix_lumen_notice_to_twitter_user_twitter_username', table_name='lumen_notice_to_twitter_user')
    op.drop_table('lumen_notice_to_twitter_user')
    op.drop_index('endpoint', table_name='twitter_ratestate')
    op.drop_index('ix_twitter_ratestate_endpoint', table_name='twitter_ratestate')
    op.drop_index('ix_twitter_ratestate_is_exhausted', table_name='twitter_ratestate')
    op.drop_index('ix_twitter_ratestate_user_id', table_name='twitter_ratestate')
    op.drop_table('twitter_ratestate')
    op.drop_index('id', table_name='archived_comments')
    op.drop_index('ix_archived_comments_created_at', table_name='archived_comments')
    op.drop_index('ix_archived_comments_post_id', table_name='archived_comments')
    op.drop_index('ix_archived_comments_subreddit_id', table_name='archived_comments')
    op.drop_index('ix_archived_comments_user_id', table_name='archived_comments')
    op.drop_table('archived_comments')
    op.drop_index('id', table_name='posts')
    op.drop_index('ix_posts_created_at', table_name='posts')
    op.drop_index('ix_posts_subreddit_id', table_name='posts')
    op.drop_table('posts')
    op.drop_index('id', table_name='comments')
    op.drop_index('ix_comments_created_at', table_name='comments')
    op.drop_index('ix_comments_post_id', table_name='comments')
    op.drop_index('ix_comments_subreddit_id', table_name='comments')
    op.drop_index('ix_comments_subreddit_id_created_at', table_name='comments')
    op.drop_index('ix_comments_user_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_experiment_thing_snapshots_created_at', table_name='experiment_thing_snapshots')
    op.drop_index('ix_experiment_thing_snapshots_experiment_id', table_name='experiment_thing_snapshots')
    op.drop_index('ix_experiment_thing_snapshots_experiment_thing_id', table_name='experiment_thing_snapshots')
    op.drop_table('experiment_thing_snapshots')
    op.drop_index('ix_twitter_unshortened_urls_record_created_at', table_name='twitter_unshortened_urls')
    op.drop_table('twitter_unshortened_urls')
    op.drop_index('ix_event_hooks_created_at', table_name='event_hooks')
    op.drop_index('ix_event_hooks_experiment_id', table_name='event_hooks')
    op.drop_index('ix_event_hooks_name', table_name='event_hooks')
    op.drop_table('event_hooks')
    op.drop_index('ix_twitter_users_not_found_id', table_name='twitter_users')
    op.drop_index('ix_twitter_users_screen_name', table_name='twitter_users')
    op.drop_table('twitter_users')
    op.drop_index('ix_praw_keys_authorized_user_id', table_name='praw_keys')
    op.drop_index('ix_praw_keys_authorized_username', table_name='praw_keys')
    op.drop_index('ix_praw_keys_created_at', table_name='praw_keys')
    op.drop_table('praw_keys')
    op.drop_index('id', table_name='mod_actions')
    op.drop_index('ix_mod_actions_created_at', table_name='mod_actions')
    op.drop_index('ix_mod_actions_subreddit_id', table_name='mod_actions')
    op.drop_index('ix_mod_actions_target_author', table_name='mod_actions')
    op.drop_table('mod_actions')
    op.drop_index('ix_experiment_things_created_at', table_name='experiment_things')
    op.drop_index('ix_experiment_things_experiment_id', table_name='experiment_things')
    op.drop_index('ix_experiment_things_object_created', table_name='experiment_things')
    op.drop_index('ix_experiment_things_query_index', table_name='experiment_things')
    op.drop_table('experiment_things')
    op.drop_index('ix_experiment_actions_action', table_name='experiment_actions')
    op.drop_index('ix_experiment_actions_action_object_id', table_name='experiment_actions')
    op.drop_index('ix_experiment_actions_action_subject_id', table_name='experiment_actions')
    op.drop_index('ix_experiment_actions_created_at', table_name='experiment_actions')
    op.drop_index('ix_experiment_actions_experiment_id', table_name='experiment_actions')
    op.drop_index('ix_experiment_actions_praw_key_id', table_name='experiment_actions')
    op.drop_table('experiment_actions')
    op.drop_index('ix_twitter_user_snapshots_twitter_not_found_id', table_name='twitter_user_snapshots')
    op.drop_index('ix_twitter_user_snapshots_twitter_user_id', table_name='twitter_user_snapshots')
    op.drop_table('twitter_user_snapshots')
    op.drop_table('twitter_tokens')
    op.drop_table('lumen_notices')
    op.drop_index('name', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_experiments_created_at', table_name='experiments')
    op.drop_index('ix_experiments_name', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('ix_front_pages_created_at', table_name='front_pages')
    op.drop_table('front_pages')
    op.drop_index('ix_lumen_notice_expanded_urls_notice_id', table_name='lumen_notice_expanded_urls')
    op.drop_table('lumen_notice_expanded_urls')
    op.drop_index('ix_subreddit_pages_created_at', table_name='subreddit_pages')
    op.drop_table('subreddit_pages')
    op.drop_index('id', table_name='subreddits')
    op.drop_index('ix_subreddits_created_at', table_name='subreddits')
    op.drop_table('subreddits')
    op.drop_table('alembic_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alembic_version',
    sa.Column('version_num', mysql.VARCHAR(length=32), nullable=False),
    sa.PrimaryKeyConstraint('version_num'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('subreddits',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_subreddits_created_at', 'subreddits', ['created_at'], unique=False)
    op.create_index('id', 'subreddits', ['id'], unique=True)
    op.create_table('subreddit_pages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('page_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('page_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('subreddit_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('is_utc', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_subreddit_pages_created_at', 'subreddit_pages', ['created_at'], unique=False)
    op.create_table('lumen_notice_expanded_urls',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('notice_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('original_url', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('expanded_url', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('number_of_hops', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_lumen_notice_expanded_urls_notice_id', 'lumen_notice_expanded_urls', ['notice_id'], unique=False)
    op.create_table('front_pages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('page_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('page_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_utc', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_front_pages_created_at', 'front_pages', ['created_at'], unique=False)
    op.create_table('experiments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('controller', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('settings_json', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_experiments_name', 'experiments', ['name'], unique=False)
    op.create_index('ix_experiments_created_at', 'experiments', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('name', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('first_seen', mysql.DATETIME(), nullable=True),
    sa.Column('last_seen', mysql.DATETIME(), nullable=True),
    sa.Column('user_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'users', ['name'], unique=True)
    op.create_table('lumen_notices',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('record_created_at', mysql.DATETIME(), nullable=True),
    sa.Column('date_received', mysql.DATETIME(), nullable=True),
    sa.Column('sender', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('principal', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('recipient', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('notice_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('CS_parsed_usernames', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('twitter_tokens',
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('oauth_token', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('oauth_token_secret', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('twitter_user_snapshots',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('twitter_user_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('twitter_not_found_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('record_created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_json', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_twitter_user_snapshots_twitter_user_id', 'twitter_user_snapshots', ['twitter_user_id'], unique=False)
    op.create_index('ix_twitter_user_snapshots_twitter_not_found_id', 'twitter_user_snapshots', ['twitter_not_found_id'], unique=False)
    op.create_table('experiment_actions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('experiment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('praw_key_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('action_subject_type', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('action_subject_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('action_object_type', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('action_object_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('metadata_json', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('action', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_experiment_actions_praw_key_id', 'experiment_actions', ['praw_key_id'], unique=False)
    op.create_index('ix_experiment_actions_experiment_id', 'experiment_actions', ['experiment_id'], unique=False)
    op.create_index('ix_experiment_actions_created_at', 'experiment_actions', ['created_at'], unique=False)
    op.create_index('ix_experiment_actions_action_subject_id', 'experiment_actions', ['action_subject_id'], unique=False)
    op.create_index('ix_experiment_actions_action_object_id', 'experiment_actions', ['action_object_id'], unique=False)
    op.create_index('ix_experiment_actions_action', 'experiment_actions', ['action'], unique=False)
    op.create_table('experiment_things',
    sa.Column('id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('object_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('experiment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('object_created', mysql.DATETIME(), nullable=True),
    sa.Column('metadata_json', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('query_index', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_experiment_things_query_index', 'experiment_things', ['query_index'], unique=False)
    op.create_index('ix_experiment_things_object_created', 'experiment_things', ['object_created'], unique=False)
    op.create_index('ix_experiment_things_experiment_id', 'experiment_things', ['experiment_id'], unique=False)
    op.create_index('ix_experiment_things_created_at', 'experiment_things', ['created_at'], unique=False)
    op.create_table('mod_actions',
    sa.Column('id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_utc', mysql.DATETIME(), nullable=True),
    sa.Column('subreddit_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('mod', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('target_author', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('action', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('target_fullname', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('action_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_mod_actions_target_author', 'mod_actions', ['target_author'], unique=False)
    op.create_index('ix_mod_actions_subreddit_id', 'mod_actions', ['subreddit_id'], unique=False)
    op.create_index('ix_mod_actions_created_at', 'mod_actions', ['created_at'], unique=False)
    op.create_index('id', 'mod_actions', ['id'], unique=True)
    op.create_table('praw_keys',
    sa.Column('id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('access_token', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('scope', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('refresh_token', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('authorized_user_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('authorized_username', mysql.VARCHAR(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_praw_keys_created_at', 'praw_keys', ['created_at'], unique=False)
    op.create_index('ix_praw_keys_authorized_username', 'praw_keys', ['authorized_username'], unique=False)
    op.create_index('ix_praw_keys_authorized_user_id', 'praw_keys', ['authorized_user_id'], unique=False)
    op.create_table('twitter_users',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('not_found_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('screen_name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('record_created_at', mysql.DATETIME(), nullable=True),
    sa.Column('lang', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('user_state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('CS_oldest_tweets_archived', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('last_attempted_process', mysql.DATETIME(), nullable=True),
    sa.Column('user_rand', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_twitter_users_screen_name', 'twitter_users', ['screen_name'], unique=False)
    op.create_index('ix_twitter_users_not_found_id', 'twitter_users', ['not_found_id'], unique=False)
    op.create_table('event_hooks',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('experiment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('call_when', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('caller_controller', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('caller_method', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('callee_module', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('callee_controller', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('callee_method', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_event_hooks_name', 'event_hooks', ['name'], unique=False)
    op.create_index('ix_event_hooks_experiment_id', 'event_hooks', ['experiment_id'], unique=False)
    op.create_index('ix_event_hooks_created_at', 'event_hooks', ['created_at'], unique=False)
    op.create_table('twitter_unshortened_urls',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('short_url', mysql.TEXT(), nullable=True),
    sa.Column('unshortened_url', mysql.TEXT(), nullable=True),
    sa.Column('error_unshortening', mysql.TINYTEXT(), nullable=True),
    sa.Column('record_created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_twitter_unshortened_urls_record_created_at', 'twitter_unshortened_urls', ['record_created_at'], unique=False)
    op.create_table('experiment_thing_snapshots',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('experiment_thing_id', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('object_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('experiment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('metadata_json', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_experiment_thing_snapshots_experiment_thing_id', 'experiment_thing_snapshots', ['experiment_thing_id'], unique=False)
    op.create_index('ix_experiment_thing_snapshots_experiment_id', 'experiment_thing_snapshots', ['experiment_id'], unique=False)
    op.create_index('ix_experiment_thing_snapshots_created_at', 'experiment_thing_snapshots', ['created_at'], unique=False)
    op.create_table('comments',
    sa.Column('id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_utc', mysql.DATETIME(), nullable=True),
    sa.Column('subreddit_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('post_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('comment_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_index('ix_comments_subreddit_id_created_at', 'comments', ['subreddit_id', 'created_at'], unique=False)
    op.create_index('ix_comments_subreddit_id', 'comments', ['subreddit_id'], unique=False)
    op.create_index('ix_comments_post_id', 'comments', ['post_id'], unique=False)
    op.create_index('ix_comments_created_at', 'comments', ['created_at'], unique=False)
    op.create_index('id', 'comments', ['id'], unique=True)
    op.create_table('posts',
    sa.Column('id', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('subreddit_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('created', mysql.DATETIME(), nullable=True),
    sa.Column('post_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('comment_data', mysql.LONGTEXT(), nullable=True),
    sa.Column('comments_queried_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_posts_subreddit_id', 'posts', ['subreddit_id'], unique=False)
    op.create_index('ix_posts_created_at', 'posts', ['created_at'], unique=False)
    op.create_index('id', 'posts', ['id'], unique=True)
    op.create_table('archived_comments',
    sa.Column('id', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_utc', mysql.DATETIME(), nullable=True),
    sa.Column('subreddit_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('post_id', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('user_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('comment_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_archived_comments_user_id', 'archived_comments', ['user_id'], unique=False)
    op.create_index('ix_archived_comments_subreddit_id', 'archived_comments', ['subreddit_id'], unique=False)
    op.create_index('ix_archived_comments_post_id', 'archived_comments', ['post_id'], unique=False)
    op.create_index('ix_archived_comments_created_at', 'archived_comments', ['created_at'], unique=False)
    op.create_index('id', 'archived_comments', ['id'], unique=True)
    op.create_table('twitter_ratestate',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('endpoint', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('is_exhausted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('checkin_due', mysql.DATETIME(), nullable=True),
    sa.Column('reset_time', mysql.DATETIME(), nullable=True),
    sa.Column('limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('remaining', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('resources', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_twitter_ratestate_user_id', 'twitter_ratestate', ['user_id'], unique=False)
    op.create_index('ix_twitter_ratestate_is_exhausted', 'twitter_ratestate', ['is_exhausted'], unique=False)
    op.create_index('ix_twitter_ratestate_endpoint', 'twitter_ratestate', ['endpoint'], unique=False)
    op.create_index('endpoint', 'twitter_ratestate', ['is_exhausted'], unique=False)
    op.create_table('lumen_notice_to_twitter_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('record_created_at', mysql.DATETIME(), nullable=True),
    sa.Column('notice_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('twitter_username', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('twitter_user_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('CS_account_archived', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_lumen_notice_to_twitter_user_twitter_username', 'lumen_notice_to_twitter_user', ['twitter_username'], unique=False)
    op.create_index('ix_lumen_notice_to_twitter_user_twitter_user_id', 'lumen_notice_to_twitter_user', ['twitter_user_id'], unique=False)
    op.create_index('ix_lumen_notice_to_twitter_user_notice_id', 'lumen_notice_to_twitter_user', ['notice_id'], unique=False)
    op.create_table('twitter_fills',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('record_created_at', mysql.DATETIME(), nullable=True),
    sa.Column('fill_type', mysql.TINYTEXT(), nullable=True),
    sa.Column('fill_start_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('job_state', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_twitter_fills_user_id', 'twitter_fills', ['user_id'], unique=False)
    op.create_index('ix_twitter_fills_record_created_at', 'twitter_fills', ['record_created_at'], unique=False)
    op.create_table('twitter_statuses',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('record_created_at', mysql.DATETIME(), nullable=True),
    sa.Column('status_data', mysql.MEDIUMTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_twitter_statuses_user_id', 'twitter_statuses', ['user_id'], unique=False)
    op.create_index('ix_twitter_statuses_record_created_at', 'twitter_statuses', ['record_created_at'], unique=False)
    op.create_index('ix_twitter_statuses_created_at', 'twitter_statuses', ['created_at'], unique=False)
    op.drop_table('edits')
    # ### end Alembic commands ###
