"""add editcout_quality

Revision ID: a76f635de7a3
Revises: 4d282492c5e4
Create Date: 2019-04-03 17:36:37.411923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76f635de7a3'
down_revision = '4d282492c5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('user_editcount_quality', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'user_editcount_quality')
    # ### end Alembic commands ###
