"""pageTitle to edits

Revision ID: e38012f5b2e8
Revises: 489406e737e4
Create Date: 2019-04-05 10:54:14.781372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e38012f5b2e8'
down_revision = '489406e737e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edits_sync',
    sa.Column('edits_sync_id', sa.Integer(), nullable=False),
    sa.Column('edit_id', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edit_id'], ['edits.edit_id'], ),
    sa.PrimaryKeyConstraint('edits_sync_id'),
    mysql_charset='utf8',
    mysql_collate='utf8_general_ci',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_edits_sync_synced_at'), 'edits_sync', ['synced_at'], unique=False)
    op.add_column('edits', sa.Column('pageTitle', mysql.TINYTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('edits', 'pageTitle')
    op.drop_index(op.f('ix_edits_sync_synced_at'), table_name='edits_sync')
    op.drop_table('edits_sync')
    # ### end Alembic commands ###
