# these min revs are determined by finding the earliest revisions in 2019 https://quarry.wmflabs.org/query/34842
langs:
  fa:
    min_rev_id: 25800000
    groups:
      newcomer:
        experience_levels:
          - bin_0
        user_count: 120
      experienced:
        experience_levels:
          - bin_90
          - bin_180
          - bin_365
          - bin_730
          - bin_1460
          - bin_2920
        user_count: 2400
  ar:
    min_rev_id: 33850000
    groups:
      newcomer:
        experience_levels:
          - bin_0
        user_count: 1750
  de:
    min_rev_id: 187110000
    groups:
      newcomer:
        experience_levels:
          - bin_0
        user_count: 3000
  pl:
    min_rev_id: 56333000
    groups:
      newcomer:
        experience_levels:
          - bin_0
        user_count: 800
      experienced:
        experience_levels:
          - bin_90
          - bin_180
          - bin_365
          - bin_730
          - bin_1460
          - bin_2920
        user_count: 2400


dirs:
  project: /data/project/thankee
  output: historical_output
  thankers: thankers_to_exclude

experiment_start_date: 2019-07-03
observation_back_days: 84
min_edit_count: 4
namespace_fn: non-talk
