langs:
  en:
    consented_file_raw: en_consent_6_26.csv
    consented_file: en_consent_6_26_clean.csv
    survey_file_raw: en_survey_6_26.csv
    survey_file: en_survey_6_26_clean.csv
    superthanker_file: en_superthankers.csv
dirs:
  project: /home/paprika/Tresors/CivilServant/projects/wikipedia-integration/gratitude-study/Data Drills/thanker_hardlaunch
  input: julia_input
  historical_output: historical
  merged_output: historical_survey_merged
  merged_no_survey_output: historical_survey_merged_consented_no_survey
  superthanker_merged_output: historical_survey_superthanker_merged
experiment_start_date: 2019-06-26
observation_back_days: 84
