# these min revs are determined by finding the earliest revisions in 2019 https://quarry.wmflabs.org/query/34842
langs:
  fa:
    min_rev_id: 27840000
    groups:
      newcomer:
        experience_levels:
          - bin_0
        user_count: 20
      experienced:
        experience_levels:
          - bin_90
          - bin_180
          - bin_365
          - bin_730
          - bin_1460
          - bin_2920
        user_count: 20
  de:
    min_rev_id: 187110000
    groups:
      newcomer:
        experience_levels:
          - bin_0
        user_count: 20
      experienced:
        experience_levels:
          - bin_90
          - bin_180
          - bin_365
          - bin_730
          - bin_1460
          - bin_2920
        user_count: 20

dirs:
  project: /home/paprika/Tresors/CivilServant/projects/wikipedia-integration/gratitude-study/Data Drills/thankee
  output: historical_output
  thankers: thankers_to_exclude


experiment_start_date: 2019-06-26
max_onboarders_to_check: 80
min_edit_count: 4
namespace_fn: non-talk
observation_back_days: 84
