langs:
  pl:
    consented_file_raw: pl_consent_6_26.csv
    consented_file: pl_consent_6_26_clean.csv
    survey_file_raw: pl_survey_6_26.csv
    survey_file: pl_survey_6_26_clean.csv
    superthanker_file: pl_superthankers.csv
  ar:
    consented_file_raw: ar_consent_6_26.csv
    consented_file: ar_consent_6_26_clean.csv
    survey_file_raw: ar_survey_6_26.csv
    survey_file: ar_survey_6_26_clean.csv
    superthanker_file: ar_superthankers.csv
  de:
    consented_file_raw: de_consent_6_26.csv
    consented_file: de_consent_6_26_clean.csv
    survey_file_raw: de_survey_6_26.csv
    survey_file: de_survey_6_26_clean.csv
    superthanker_file: de_superthankers.csv
dirs:
  project: /home/paprika/Tresors/CivilServant/projects/wikipedia-integration/gratitude-study/Data Drills/thanker_hardlaunch
  input: julia_input
  historical_output: historical
  merged_output: historical_survey_merged
  merged_no_survey_output: historical_survey_merged_consented_no_survey
  superthanker_merged_output: historical_survey_superthanker_merged
experiment_start_date: 2019-06-13
observation_back_days: 84
