# these min revs are determined by finding the earliest revisions in 2019 https://quarry.wmflabs.org/query/34842
langs:
  pl:
    min_rev_id: 57140000
    groups:
      newcomer:
        experience_levels:
          - bin_0
        user_count: 950
      experienced:
        experience_levels:
          - bin_90
          - bin_180
          - bin_365
          - bin_730
          - bin_1460
          - bin_2920
        user_count: 2550
  ar:
    min_rev_id: 37050000
    groups:
      newcomer:
        experience_levels:
          - bin_0
        user_count: 1900
  de:
    min_rev_id: 190780000
    groups:
      newcomer:
        experience_levels:
          - bin_0
        user_count: 3000


dirs:
  project: /data/project/thankee
  output: historical_output
  thankers: thankers_to_exclude

experiment_start_date: 2019-10-27
observation_back_days: 90
min_edit_count: 4
namespace_fn: non-talk-non-user
