ID: anonymized_id
trust_1: pre_newcomer_capability
trust_3: pre_newcomer_intent
burnout_1: pre_emotionally_draining
burnout_2: pre_feel_positive
activities_3: pre_monitoring_damaging_content
activities_4: pre_mentoring
lang: lang
