project_dir: /data/project/thanker/
randomizations_dir: liasons
randomizations_file: liason-accounts-superthankers.csv


csv_db_map:
  thing_id: anonymized_id


cols_to_save:
    - user_name
    - lang
