project_dir: /data/project/thankee
randomizations_dir: randomization_output
randomizations_file: thanks-recipient-randomizations-20190730.csv

cols_to_save:
  - created_at
  - lang
  - user_id
  - user_name
  - user_registration
  - user_editcount
  - user_editcount_quality
  - user_experience_level
  - num_prev_thanks_pre_sample
  - labor_hours_84_days_pre_sample
  - has_email
  - user_completed
  - user_included
