project_dir: /home/paprika/Tresors/CivilServant/projects/wikipedia-integration/gratitude-study/Data Drills
randomizations_dir: randomization_output
randomizations_file: all-thanker-randomization-datadrill-20190427.csv


csv_db_map:
  thing_id: anonymized_id
