project_dir: /home/paprika/Tresors/CivilServant/projects/wikipedia-integration/gratitude-study/Data Drills/thankee
randomizations_dir: randomization_output
randomizations_file: thanks-recipient-randomizations-20190531.csv


csv_db_map:
  thing_id: anonymized_id


cols_to_save:
    - user_name
    - anonymized_id
    - user_id
    - user_editcount
    - user_editcount_quality
    - randomization_block_id
    - randomization_block_size
